[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.16.1"
  NODE_ENV = "production"
  OPENFISCA_INTERNAL_ROOT_URL = "https://openfisca.mes-aides.1jeune1solution.gouv.fr"
  OPENFISCA_PUBLIC_ROOT_URL = "https://openfisca.mes-aides.1jeune1solution.gouv.fr"
  SESSION_SECRET = "maas-group-secret-key"
  SMS_SERVICE_SHOW = "false"

[[redirects]]
  from = "/api/*"
  to = "https://mes-aides.1jeune1solution.beta.gouv.fr/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
